name: resisto
channels:
  - conda-forge
  - bioconda
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - aom=3.9.1=h7bae524_0
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - blosc=1.21.6=h7dd00d9_1
  - brotli=1.1.0=h5505292_3
  - brotli-bin=1.1.0=h5505292_3
  - brotli-python=1.1.0=py311h155a34a_3
  - brunsli=0.1=h97083b6_1
  - bzip2=1.0.8=h99b78c6_7
  - c-blosc2=2.21.2=hb5916c8_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py311h3a79f62_0
  - charls=2.4.2=h13dd4ca_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.2=py311h210dab8_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - dav1d=1.2.1=hb547adb_0
  - debugpy=1.8.15=py311ha59bd64_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - dython=0.7.9=pyhd8ed1ab_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - fonttools=4.59.0=py311h2fe624c_0
  - freetype=2.13.3=hce30654_1
  - giflib=5.2.2=h93a5062_0
  - h2=4.2.0=pyhd8ed1ab_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.10=pyhd8ed1ab_1
  - imagecodecs=2025.8.2=py311h34e99b9_4
  - imageio=2.37.0=pyhfb79c49_0
  - imbalanced-learn=0.13.0=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=9.4.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.1=pyhd8ed1ab_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - jxrlib=1.1=h93a5062_3
  - kiwisolver=1.4.8=py311h210dab8_1
  - krb5=1.21.3=h237132a_0
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libaec=1.1.4=h51d1e36_0
  - libavif16=1.3.0=hb06b76e_2
  - libblas=3.9.0=32_h10e41b3_openblas
  - libbrotlicommon=1.1.0=h5505292_3
  - libbrotlidec=1.1.0=h5505292_3
  - libbrotlienc=1.1.0=h5505292_3
  - libcblas=3.9.0=32_hb3479ef_openblas
  - libcxx=20.1.8=hf598326_1
  - libdeflate=1.24=h5773f1b_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.6=h1da3d7d_1
  - libfreetype=2.13.3=hce30654_1
  - libfreetype6=2.13.3=h1d14073_1
  - libgfortran=5.0.0=14_2_0_h6c33f7e_103
  - libgfortran5=14.2.0=h6c33f7e_103
  - libhwy=1.3.0=hf6a9ce8_0
  - libjpeg-turbo=3.1.0=h5505292_0
  - libjxl=0.11.1=h7274d02_4
  - liblapack=3.9.0=32_hc9a63f6_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libopenblas=0.3.30=openmp_hf332438_0
  - libpng=1.6.50=h3783ad8_0
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.50.3=hf8de324_0
  - libtiff=4.7.0=h2f21f7c_5
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libzlib=1.3.1=h8359307_2
  - libzopfli=1.0.3=h9f76cd9_0
  - littleutils=0.2.4=pyhd8ed1ab_1
  - llvm-openmp=20.1.8=hbb9b287_0
  - lz4-c=1.10.0=h286801f_1
  - matplotlib=3.10.3=py311ha1ab1f8_0
  - matplotlib-base=3.10.3=py311h031da69_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mpmath=1.3.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.5=pyhe01879c_0
  - openjpeg=2.5.3=h8a3d83b_0
  - openpyxl=3.1.5=py311hfb527b5_1
  - openssl=3.5.3=h5503f6c_1
  - outdated=0.2.2=pyhd8ed1ab_2
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.1=py311hff7e5bb_0
  - pandas-flavor=0.7.0=pyhd8ed1ab_0
  - parso=0.8.4=pyhd8ed1ab_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py311hb9ba9e9_0
  - pingouin=0.5.5=pyhd8ed1ab_1
  - pip=25.1.1=pyh8b19718_0
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py311h917b07b_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.13=hc22306f_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytz=2025.2=pyhd8ed1ab_0
  - pywavelets=1.9.0=py311h8b6d4dd_1
  - pyzmq=27.0.0=py311h01f2145_0
  - qhull=2020.2=h420ef59_5
  - rav1e=0.7.1=h0716509_3
  - readline=8.2=h1d1bf99_2
  - requests=2.32.4=pyhd8ed1ab_0
  - scikit-image=0.25.2=py311hdb8e4fa_2
  - scikit-learn=1.6.1=py311h47fa2fb_0
  - scipy=1.16.0=py311h53b02f6_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - sklearn-compat=0.1.3=pyhd8ed1ab_0
  - snappy=1.2.2=hd121638_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py311h9dc9093_0
  - svt-av1=3.1.2=h12ba402_0
  - tabulate=0.9.0=pyhd8ed1ab_2
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tifffile=2025.9.20=pyhd8ed1ab_0
  - tk=8.6.13=h892fb3f_2
  - tornado=6.5.1=py311h917b07b_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py311h917b07b_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - xarray=2025.7.1=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - zeromq=4.3.5=hc1bb282_7
  - zfp=1.0.1=hfd287c0_3
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib-ng=2.2.5=hf787086_0
  - zstandard=0.23.0=py311h917b07b_2
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - numpy==2.2.6
      - opencv-python==4.12.0.88
prefix: /Users/alzorrcarri/miniconda3/envs/machlear
